Repository appwex/izzy-health, pull requests merged in 2022-12, with the labels that each got.

#8 Setup Next App
  .eslintrc.json
  .prettierrc
  README.md
  jsconfig.json
  next.config.js
  package.json
  pages/_app.js
  pages/_document.js
  pages/home/Home.js
  pages/home/Home.module.scss
  pages/home/index.js
  pages/index.js
  pages/stories/Story.module.scss
  pages/stories/index.js
  src/components/stories/Stories.js
  src/components/stories/Stories.module.scss
  src/components/stories/index.js
  src/styles/colors.scss
  src/styles/common.scss
  src/styles/globals.scss
  yarn.lock
Labels: good first issue

#12 Add Button Component #5
  docs/Code_Contribute_Guidelines.md
  pages/stories/index.js
  pages/stories/izzyButton.js
  src/components/izzyButton/IzzyButton.js
  src/components/izzyButton/IzzyButton.md
  src/components/izzyButton/IzzyButton.module.scss
  src/components/izzyButton/index.js
  src/styles/colors.scss
Labels: enhancement, ready for review

#13 first commit (#2)
  package-lock.json
  pages/stories/index.js
  pages/stories/navbar.js
  public/background.svg
  src/assets/svg/logo.svg
  src/components/navbar/navbar.js
  src/components/navbar/navbar.module.scss
  yarn.lock
Labels: ready for review

#17 Add Structure docs
  docs/Structure.md
Labels: documentation

#20 ADD TEAM SECTION #6
  pages/home/Home.js
  pages/stories/care-section.js
  pages/stories/index.js
  src/assets/svg/index.js
  src/assets/svg/nutritionist.svg
  src/assets/svg/physician.svg
  src/assets/svg/psychologist.svg
  src/components/careSection/careSection.js
  src/components/careSection/careSection.module.scss
  src/styles/colors.scss
  yarn.lock
Labels: UI, ready for review

#15 Ih/demandtech/combat section
  package-lock.json
  pages/home/Home.js
  pages/stories/combat.js
  pages/stories/index.js
  pages/stories/modal.js
  src/components/combat/Combat.js
  src/components/combat/Combat.module.scss
  src/components/combat/index.js
  src/components/izzyButton/IzzyButton.js
  src/styles/common.scss
  yarn.lock
Labels: ready for review
